global using Discord;
global using Discord.Commands;
global using Discord.WebSocket;
global using Microsoft.Extensions.DependencyInjection;
global using Newtonsoft.Json.Linq;
global using Steam.Models.SteamCommunity;
global using SteamWebAPI2.Interfaces;
global using SteamWebAPI2.Utilities;
global using System.Reflection;
